mvcAuthentication/Models/Context/Context.cs
using Microsoft.EntityFrameworkCore;
using mvcAuthentication.Models.Entities;

namespace mvcAuthentication.Models.Context
{
    public class Context:DbContext
    {
        public Context()
        {

        }
        public Context(DbContextOptions<Context> options) : base(options)
        {



        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=DESKTOP-ORUQO20;Database=nrm1Autentication;Trusted_Connection=True;TrustServerCertificate=True;");
        }

        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Personel> Personels { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
    }
}

mvcAuthentication/Models/Entities/Department.cs
using System.ComponentModel.DataAnnotations;

namespace mvcAuthentication.Models.Entities
{
    public class Department
    {
        [Key]
        public int DepartmentID { get; set; }
        public string? DepartmentName{ get; set; }
        public virtual List<Personel>? Personel{ get; set; }
    }
}

mvcAuthentication/Models/Entities/Manager.cs
using System.ComponentModel.DataAnnotations;

namespace mvcAuthentication.Models.Entities
{
    public class Manager
    {
        [Key]
        public int ManagerID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}

mvcAuthentication/Models/Entities/Personel.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace mvcAuthentication.Models.Entities
{
    public class Personel
    {
        public int PersonelID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        [ForeignKey("Department")]
        public int DepartmentID { get; set; }
        public virtual Department? Department { get; set; }
    }
}

mvcAuthentication/Models/ErrorViewModel.cs
namespace mvcAuthentication.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

mvcAuthentication/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;
using mvcAuthentication.Models.Context;
using mvcAuthentication.Models.Entities;

namespace mvcAuthentication.Controllers
{
    public class DepartmentController : Controller
    {
        Context db = new Context();
        public IActionResult Index()
        {
            return View(db.Departments.ToList());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Department department)
        {
            if (ModelState.IsValid)
            {
                db.Departments.Add(department);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
           
            
            return View();
        }
    }
}

mvcAuthentication/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using mvcAuthentication.Models;
using System.Diagnostics;

namespace mvcAuthentication.Controllers
{
    //[Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

mvcAuthentication/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using mvcAuthentication.Models.Context;
using mvcAuthentication.Models.Entities;
using System.Security.Claims;
using System.Security.Principal;

namespace mvcAuthentication.Controllers
{
    [AllowAnonymous]
    public class LoginController : Controller
    {
        Context db=new Context();
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SignIn()
        {
            return View();
        }
        [HttpPost]
        public IActionResult SignIn(Manager mg)
        {
            var information = db.Managers.FirstOrDefault(x=>x.UserName==mg.UserName && x.Password==mg.Password);
            if (information!=null) 
            {
                //usage of claims
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name,mg.UserName)
                };

                var userIdentity=new ClaimsIdentity(claims,"Login");   //association with claim id

                ClaimsPrincipal claimsPrincipal=new ClaimsPrincipal(userIdentity); // Put useridentity in object derive ctor from Define multi-identity claim class

                HttpContext.SignInAsync(claimsPrincipal); //Creates an encrypted cookie and appends it to the valid response
                return RedirectToAction("Index","Home");
            }
            else
            {
                ViewBag.Message = "Wrong username or password:(";
            }
            return View();
        }
        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("SignIn");
        }
    }
}

mvcAuthentication/Controllers/PersonelController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using mvcAuthentication.Models.Context;
using mvcAuthentication.Models.Entities;

namespace mvcAuthentication.Controllers
{
    public class PersonelController : Controller
    {
        Context db = new Context();
        public IActionResult Index()
        {
            return View(db.Personels.Include(x=>x.Department).ToList());
        }

        public  IActionResult Create()
        {
            ViewBag.DepartmentID = new SelectList(db.Departments.ToList(),"DepartmentID", "DepartmentName");
            return View();
        }
        [HttpPost]
        public IActionResult Create(Personel personel)
        {
            if (ModelState.IsValid)
            {
                db.Personels.Add(personel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

mvcAuthentication/Views/Department/Create.cshtml
@model mvcAuthentication.Models.Entities.Department

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Department</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DepartmentName" class="control-label"></label>
                <input asp-for="DepartmentName" class="form-control" />
                <span asp-validation-for="DepartmentName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

mvcAuthentication/Views/Department/Index.cshtml
@model IEnumerable<mvcAuthentication.Models.Entities.Department>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DepartmentName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DepartmentName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.DepartmentID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.DepartmentID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.DepartmentID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

mvcAuthentication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

mvcAuthentication/Views/Login/SignIn.cshtml
@{
    ViewData["Title"] = "SignIn";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}
<h1>@ViewBag.Message</h1>
<form action="SignIn" class="signin-form" method="post">
    <div class="form-group">
        <input type="text" class="form-control" placeholder="Username" required name="UserName">
    </div>
    <div class="form-group">
        <input id="password-field" type="password" class="form-control" placeholder="Password" required name="Password">
        <span toggle="#password-field" class="fa fa-fw fa-eye field-icon toggle-password"></span>
    </div>
    <div class="form-group">
        <button type="submit" class="form-control btn btn-primary submit px-3">Sign In</button>
    </div>
    <div class="form-group d-md-flex">
        <div class="w-50">
            <label class="checkbox-wrap checkbox-primary">
                Remember Me
                <input type="checkbox" checked>
                <span class="checkmark"></span>
            </label>
        </div>
        <div class="w-50 text-md-right">
            <a href="#" style="color: #fff">Forgot Password</a>
        </div>
    </div>
</form>

mvcAuthentication/Views/Personel/Create.cshtml
@model mvcAuthentication.Models.Entities.Personel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Personel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartmentID" class="control-label"></label>
                <select asp-for="DepartmentID" class ="form-control" asp-items="ViewBag.DepartmentID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

mvcAuthentication/Views/Personel/Index.cshtml
@model IEnumerable<mvcAuthentication.Models.Entities.Personel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Department)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @item.Department.DepartmentName
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.PersonelID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.PersonelID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.PersonelID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

mvcAuthentication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mvcAuthentication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/mvcAuthentication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">mvcAuthentication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="LogOut">Log Out</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personel" asp-action="Index">List of Personel</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personel" asp-action="Create">Add Personel</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">List of Department</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Create">Add Department</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - mvcAuthentication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

mvcAuthentication/Views/Shared/_LoginLayout.cshtml
<!doctype html>
<html lang="en">
<head>
	<title>Login 10</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	<link rel="stylesheet" href="/css/style.css">
    
</head>
<body class="img js-fullheight" style="background-image: url(/images/bg.jpg);">
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Login</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-6 col-lg-4">
					<div class="login-wrap p-0">
						<h3 class="mb-4 text-center">Have an account?</h3>
						@RenderBody()
						<p class="w-100 text-center">&mdash; Or Sign In With &mdash;</p>
						<div class="social d-flex text-center">
							<a href="#" class="px-2 py-2 mr-md-1 rounded"><span class="ion-logo-facebook mr-2"></span> Facebook</a>
							<a href="#" class="px-2 py-2 ml-md-1 rounded"><span class="ion-logo-twitter mr-2"></span> Twitter</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<script src="/js/jquery.min.js"></script>
	<script src="/js/popper.js"></script>
	<script src="/js/bootstrap.min.js"></script>
	<script src="/js/main.js"></script>
    
</body>
</html>